apiVersion: apps/v1
kind: Deployment
metadata:
  name: video-streaming-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: video-streaming-server
  template:
    metadata:
      labels:
        app: video-streaming-server
    spec:
      containers:
      - name: video-streaming-server
        image: arindm007/video-stream:latest
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: video-streaming-service
spec:
  selector:
    app: video-streaming-server
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: LoadBalancer
