
# Exported from Render on 2025-01-28T11:03:21Z
services:
- type: web
  name: webcam-stream
  runtime: python
  repo: https://github.com/arindm007/webcam-stream
  plan: free
  region: oregon
  buildCommand: pip install -r requirements.txt
  # startCommand: python server.py
  startCommand: gunicorn --threads 4 -b 0.0.0.0:8080 server:app
version: "1"
